# Generated by Django 4.2.16 on 2024-11-03 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Fix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('fixed_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.error')),
            ],
        ),
        migrations.AddField(
            model_name='error',
            name='programmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.programmer'),
        ),
    ]
